---

- name: git pull
  git:
    repo: git@bitbucket.org:username/repo.git
    dest: "{{ app_directory }}"
    accept_hostkey: true
    key_file: "{{ key_file }}"
    version: "{{ app_version }}"
  notify:
    - restart celery
    - restart beat
  register: code_updated

- name: Ensure app has correct user for files and restart
  become: yes
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775
    recurse: yes
  notify:
    - restart celery
    - restart beat

- name: Update configs
  template:
    src: worker_config.py.j2
    dest: "{{ app_directory }}/liaison/config/production.py"
  notify:
    - restart celery
    - restart beat
  when: code_updated.changed == true

- name: pip install
  pip:
    requirements: "{{ app_directory }}/requirements.txt"
    virtualenv: "{{ app_directory }}/venv"
  notify:
    - restart celery
    - restart beat
  when: code_updated.changed == true

- name: Ensure logs have correct user for files.
  become: yes
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    recurse: yes


###
# Restart
###

- name: Check running applications managed by supervisor
  shell: supervisorctl status
  register: supervisor_applications

- name: Restart the celery app
  supervisorctl: name=celery state=restarted
  when: supervisor_applications.stdout.find('{{ celery_application_name }}') != -1
