"""empty message

Revision ID: 18081e8b53eb
Revises: 34afcf9eec6d
Create Date: 2015-09-07 19:58:45.869609

"""

# revision identifiers, used by Alembic.
revision = '18081e8b53eb'
down_revision = '34afcf9eec6d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatches', sa.Column('adjusted_data', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatches', 'adjusted_data')
    ### end Alembic commands ###
