"""empty message

Revision ID: 280bb64cc523
Revises: 11a66ebc4c48
Create Date: 2015-09-12 17:57:26.271907

"""

# revision identifiers, used by Alembic.
revision = '280bb64cc523'
down_revision = '11a66ebc4c48'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatcher_data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatcher_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original_data', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('adjusted_data', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('dispatcher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], [u'dispatches.id'], name=u'dispatcher_data_dispatcher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'dispatcher_data_pkey')
    )
    ### end Alembic commands ###
