"""empty message

Revision ID: 34838ace5785
Revises: 51445f4ad17
Create Date: 2015-06-21 14:42:47.998832

"""

# revision identifiers, used by Alembic.
revision = '34838ace5785'
down_revision = '51445f4ad17'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misc',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('data', postgresql.JSON(), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('misc')
    ### end Alembic commands ###
