"""empty message

Revision ID: 34afcf9eec6d
Revises: 34838ace5785
Create Date: 2015-09-05 13:16:38.108129

"""

# revision identifiers, used by Alembic.
revision = '34afcf9eec6d'
down_revision = '34838ace5785'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatcher_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_data', postgresql.JSON(), nullable=True),
    sa.Column('adjusted_data', postgresql.JSON(), nullable=True),
    sa.Column('dispatcher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatcher_data')
    ### end Alembic commands ###
