"""empty message

Revision ID: 51445f4ad17
Revises: None
Create Date: 2015-05-16 17:25:27.857215

"""

# revision identifiers, used by Alembic.
revision = '51445f4ad17'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('subaccount_name', sa.String(length=255), nullable=True),
    sa.Column('dedicated_ip', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('active', sa.SmallInteger(), nullable=True),
    sa.Column('accepted_terms', sa.SmallInteger(), nullable=True, default=0),
    sa.Column('default_from_email', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=255), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.Column('auto_text', sa.Integer(), nullable=True, default=0),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unsubscribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('manual', sa.Integer(), nullable=True, default=0),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('activation_key', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=False), nullable=True),
    sa.Column('current_login_ip', sa.String(length=255), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('selector_col_name', sa.String(length=255), nullable=True),
    sa.Column('from_email_dd', sa.String(length=255), nullable=True),
    sa.Column('from_name_dd', sa.String(length=255), nullable=True),
    sa.Column('reply_to_dd', sa.String(length=255), nullable=True),
    sa.Column('to_email_dd', sa.String(length=255), nullable=True),
    sa.Column('to_name_dd', sa.String(length=255), nullable=True),
    sa.Column('from_email_ov', sa.String(length=255), nullable=True),
    sa.Column('from_name_ov', sa.String(length=255), nullable=True),
    sa.Column('reply_to_ov', sa.String(length=255), nullable=True),
    sa.Column('to_email_ov', sa.String(length=255), nullable=True),
    sa.Column('to_name_ov', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('import_data', postgresql.JSON(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('selector_col_val', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('preheader', sa.String(length=255), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_data', postgresql.JSON(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True, default=0),
    sa.Column('queued_count', sa.Integer(), nullable=True, default=0),
    sa.Column('sent_count', sa.Integer(), nullable=True, default=0),
    sa.Column('skipped_count', sa.Integer(), nullable=True, default=0),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('sends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_id', sa.String(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('dispatcher_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.Column('message', postgresql.JSON(), nullable=True),
    sa.Column('result', postgresql.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True, default=0),
    sa.Column('attempts', sa.Integer(), nullable=True, default=0),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sends_hash_id'), 'sends', ['hash_id'], unique=True)
    ### end Alembic commands ###





def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sends_hash_id'), table_name='sends')
    op.drop_table('sends')
    op.drop_table('roles_users')
    op.drop_table('dispatches')
    op.drop_table('emails')
    op.drop_table('lists')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('unsubscribes')
    op.drop_table('templates')
    op.drop_table('accounts')
    op.drop_table('roles')
    ### end Alembic commands ###
