"""empty message

Revision ID: e276b8143bd
Revises: 280bb64cc523
Create Date: 2015-09-12 18:48:33.887647

"""

# revision identifiers, used by Alembic.
revision = 'e276b8143bd'
down_revision = '280bb64cc523'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklists', sa.Column('reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('accepted_terms', sa.SmallInteger(), nullable=True, default=0))
    op.drop_column('accounts', 'accepted_terms')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklists', 'reason')
    op.drop_column('users', 'accepted_terms')
    op.add_column('accounts', sa.Column('accepted_terms', sa.SmallInteger(), nullable=True, default=0))
    ### end Alembic commands ###
