---

- name: Install Supervisor
  become: yes
  apt:
    name: supervisor
    update_cache: "{{ update_apt_cache }}"
    state: latest

- name: Install supervisor configuration file.
  become: yes
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    backup: yes
  notify: restart supervisor

- name: Ensure supervisor service is started
  become: yes
  service: name=supervisor state=started enabled=yes

